OPENAI_API_KEY = "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"
GOOGLE_SHEET_ID = "135ptaYklWDQkOkcW-luCOGbUE7zd5FbnqIDl7LVoNzE"

